import express, { Request, Response } from 'express';
import cors from 'cors';

const app = express();
app.use(cors());
app.use(express.json());

interface PeerSession {
  code: string;
  hostPublicKey: string;
  hostEndpoint: string; // e.g. "yourname.duckdns.org:51820" or "1.2.3.4:51820"
  clientPublicKey?: string;
  createdAt: number;
}

const sessions = new Map<string, PeerSession>();

app.get('/', (req: Request, res: Response) => {
  res.status(200).json({ status: 'running', activeSessions: sessions.size });
});

// Host registers its REAL public key (generated by WireGuard itself) and the
// address it's reachable at (after you've set up port forwarding / DDNS).
app.post('/register', (req: Request, res: Response) => {
  const { code, hostPublicKey, hostEndpoint } = req.body;

  if (!code || !hostPublicKey || !hostEndpoint) {
    return res.status(400).json({ message: 'Missing code, hostPublicKey, or hostEndpoint' });
  }

  sessions.set(code, { code, hostPublicKey, hostEndpoint, createdAt: Date.now() });
  console.log(`[HOST REGISTERED] Code: ${code} -> ${hostEndpoint}`);
  return res.status(200).json({ message: 'Host registered successfully' });
});

// Client looks up a code to get the host's real public key + endpoint, and
// submits its own real public key so the host operator can add it as a peer.
app.post('/pair', (req: Request, res: Response) => {
  const { code, clientPublicKey } = req.body;
  const session = sessions.get(code);

  if (!session) return res.status(404).json({ message: 'Code not found or expired' });

  if (clientPublicKey) {
    session.clientPublicKey = clientPublicKey;
  }

  return res.status(200).json({
    hostPublicKey: session.hostPublicKey,
    hostEndpoint: session.hostEndpoint,
  });
});

// Host polls/fetches this to see the pending client's real public key so it
// can be added as a WireGuard peer on the host machine.
app.get('/host/pending/:code', (req: Request, res: Response) => {
  const session = sessions.get(req.params.code);

  if (!session) return res.status(404).json({ message: 'Code not found or expired' });

  return res.status(200).json({ clientPublicKey: session.clientPublicKey ?? null });
});

// Sessions live for an hour — this is a manual pairing flow, not a live
// polling one, so codes need longer than the old 15-minute WebRTC window.
setInterval(() => {
  const now = Date.now();
  for (const [code, session] of sessions.entries()) {
    if (now - session.createdAt > 60 * 60 * 1000) {
      sessions.delete(code);
    }
  }
}, 60 * 1000);

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Pairing directory running on port ${PORT}`);
});
